### PR TITLE
Multilingual and large-v3 support

### LINKED ISSUE #1: Multilingual support
Nice work! What is needed to support multilingual model? I might give it a try.

### PR DESCRIPTION
**Pull request by Benoit9**
Closes #1

### CODE REVIEW

**Comment by pxl-th** [comment]
Thanks! BTW, does it work for you? I was about to suggest some minor changes to this PR, but even the `main` branch does not give correct answers for me anymore on something as simple as [JFK sample](https://raw.githubusercontent.com/openai/whisper/main/tests/jfk.flac)...

**Comment by Benoit9** [comment]
Yes, the code works for me, on samples I recorded.

The sample you linked to is 44.1kHz. I have the 16kHz version lying around and it's fine, with en and multilingual models.

**Comment by pxl-th** [comment]
Nevermind, I was using `tiny` model, instead of `tiny.en`.

FYI, if the sample rate is not 16kHz, it will [convert](https://github.com/JuliaNeuralGraphics/Whisper.jl/blob/1dfe98f3ec72108fb42f76937c161b295ca51805/src/Whisper.jl#L151) using ffmpeg. Same with other file formats.

**Comment by pxl-th** [comment]
Let's merge this one and I'll add optional task and language tokens in a separate PR.
Thanks for contributing!

**Comment by Benoit9** [comment]
You're welcome! That wasn't much.

**Pull request merged**
